import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Layout from "@/components/_ui/Layout"
import { MouseContextProvider } from "@/contexts/ mouse-context"
import { ThemeContextProvider } from "@/contexts/theme-context"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <MouseContextProvider>
            <Layout>{children}</Layout>
          </MouseContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
