import type { Metadata } from "next"
import { Kode_Mono, Syne_Mono } from "next/font/google"
import "./globals.css"
import Layout from "@/components/_ui/Layout"
import { MouseContextProvider } from "@/contexts/ mouse-context"
import { ThemeContextProvider } from "@/contexts/theme-context"

const bricolageGrotesque = Syne_Mono({
  display: "swap",
  preload: true,
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque",
  weight: ["400"],
})

const monoton = Kode_Mono({
  display: "swap",
  preload: true,
  subsets: ["latin"],
  variable: "--font-monoton",
  weight: ["400"],
})

export const metadata: Metadata = {
  title: "🗒️ klogs",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${monoton.variable} ${bricolageGrotesque.variable}`}>
        <ThemeContextProvider>
          <MouseContextProvider>
            <Layout>{children}</Layout>
          </MouseContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  )
}
